baseURL = 'https://josh.hrdz.us/'
defaultContentLanguage = 'en'
title = 'Josue Hernandez :: Blog'
theme = 'terminal'
pagination.pagerSize = 10
enableEmoji = true

[params]
  contentTypeName = "posts"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true
  showLanguageSelector = true
  
  [params.logo]
    logoText = "Josue Hernandez"
    logoHomeLink = "/"

[languages]
  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'

    [languages.en.params]
      subtitle = "> the world's worst blogger"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"

  [languages.es]
    languageCode = 'es-US'
    languageName = 'Español'

    [languages.es.params]
      subtitle = "> el peor de los bloggers"
      menuMore = "Ver más"
      readMore = "Leer más"
      readOtherPosts = "Leer otros posts"


